import 'recurse-brazil.just'

[no-cd]
build_AvLrcMinervaMetricSchemas:
    zsh -c "cd src/schemas/lrnp/utils && python ./main.py"
    brazil-build run env -- jest --updateSnapshot -t "LRNP Minerva Metric Schemas"
    brazil-build test

[no-cd]
init_AVLivingRoomClientHybridCommon:
    brazil-build install

[no-cd]
build_AVLivingRoomClientHybridCommon:
    brazil-build release

[no-cd]
init_AVLivingRoomClientBootstrap:
    brazil-build install

[no-cd]
build_AVLivingRoomClientBootstrap:
    npm run build

[no-cd]
build_IgnitionXJSBundle:
    brazil-build

[no-cd]
init_AVLivingRoomClient:
    brazil-build install

[no-cd]
build_AVLivingRoomClient:
    brazil-build run build-prod -- --env deviceType=Default-Ignite-XP --env sourceMap=eval-source-map

[no-cd]
build_RokuNDK:
    brazil-build

[no-cd]
pre_build_RustStdRoku:
    rm -f build/private/src/config.toml

[no-cd]
build_RustStdRoku:
    brazil-build

[no-cd]
init_Brotli:
    git checkout --force origin/Brotli-1.1.0

[no-cd]
build_Brotli:
    brazil-build

[no-cd]
init_IgnitionXRustBundle:
    #brazil-build

[no-cd]
build_IgnitionXRustBundle:
    #IGNITION_X_PATH=~/dev/i/dev/build/install build-tools/release-quick --lib
    #cargo build --bins --release --target arm-unknown-linux-gnueabi
    brazil-build

[no-cd]
release_IgnitionXRustBundle:
    for i in amzn* ignx*; do cd $i; cargo brazil publish --allow-dirty; cd -; done

[no-cd]
init_AVLivingRoomRustClient:
    brazil-build setup
    cargo brazil fetch --target all

    #brazil-build sync

[no-cd]
pre_build_AVLivingRoomRustClient:
    rm -f Cargo.lock

[no-cd]
build_AVLivingRoomRustClient:
    build-tools/bin/generate-bundles ignite-sdk

    #find build/lib/* -regex .\*amzn_av_living_room_rust_client.\*so | xargs --no-run-if-empty ls -l
    #find build/lib/* -regex .\*amzn_av_living_room_rust_client.\*so | xargs --no-run-if-empty file
    #find build/lib/* -regex .\*amzn_av_living_room_rust_client.\*so.br | xargs --no-run-if-empty file

    #cargo build -p amzn-av-living-room-rust-client --lib --features=amzn-ignx-compositron/allow_no_js_vm,amzn-ignx-compositron/use_ignx_local,amzn-ignx-compositron/debug_overlay

    #brazil-build build || true

    readelf -sW build/private/cargo-target/*/release/libamzn_av_living_room_rust_client.so | awk '/UND/ && !/WEAK/{print $8}'| sort -u

[no-cd]
test_AVLivingRoomRustClient:
    mkdir -p $HOME/devc/i/devc1/build/
    cp build/private/cargo-target/x86_64-unknown-linux-musl/release/libamzn_av_living_room_rust_client.so $HOME/devc/i/devc1/build/
    just --justfile $HOME/devc/i/devc1/justfile pv --log-level=ALL:DEBUG --set-default-native-engine=Ignite --local-native-module-path=$(realpath $HOME/devc/i/devc1/build/libamzn_av_living_room_rust_client.so) --log-file=build/log-ignite-$(date +%F-%H-%M-%S).txt

[no-cd]
release_AVLivingRoomRustClient:
    #cp -r build/lib/* $(cd ~/dev/avlrc-rel/src/AVLivingRoomClientBundle; brazil-path '[AVLivingRoomRustClient@1.0]pkg.lib')
    #ls -l $(cd ~/dev/avlrc-rel/src/AVLivingRoomClientBundle; brazil-path '[AVLivingRoomRustClient@1.0]pkg.lib')

[no-cd]
init_RustStdMuslsIgnition:
    brazil ws merge -l -p Musl-1.x || true

[no-cd]
pre_build_RustStdMuslsIgnition:
    rm -f build/private/src/{config,bootstrap}.toml

[no-cd]
build_RustStdMuslsIgnition:
    brazil-build build

[no-cd]
build_IgnitionCratesIoPatches:
    brazil-build build

[no-cd]
build_AVLivingRoomClientBundle:
    brazil-build run build -- -f Ignition-X-XP --nobytecode --noaot --nothreads --nonativebundle=false
    #strings build/lib_debug/*client-*.so|grep 'always_return_true'

[no-cd]
release_AVLivingRoomClientBundle:
    brazil-build run put-this-on-that -- --flavor Ignition-X-XP --dtid=A3VN4E5F7BBC7S --did=abcd$(whoami)abcd --stringBundles en_US

[no-cd]
build_ATVDeviceInitializationServiceDeviceConfig:
    brazil-build generate-brazil-config-root
    brazil-build test

[no-cd]
build_AVTSTestRepository:
    brazil-build release

[no-cd]
build_IgniteSdk:
    brazil-build

[no-cd]
build_RustStdBuild:
    brazil-build

[no-cd]
build_IgniteSdkArtifact:
    brazil-runtime-exec build-tools/bin/custom-build

[no-cd]
pre_build_RustStdIgnite:
    rm -f build/private/src/{config,bootstrap}.toml

[no-cd]
build_RustStdIgnite:
    brazil ws show
    brazil-build

[no-cd]
init_IgniteSdkRustExamples:
    brazil-build

[no-cd]
build_IgniteSdkRustExamples:
    brazil-build build || true
    readelf -sW build/private/cargo-target/*/release/libamzn_ignite_sdk_rust_examples.so | awk '/UND/ && !/WEAK/{print $8}'|sort -u

[no-cd]
test_IgniteSdkRustExamples:
    mkdir -p $HOME/devc/i/devc1/build/
    cp build/private/cargo-target/x86_64-unknown-linux-musl/release/libamzn_ignite_sdk_rust_examples.so $HOME/devc/i/devc1/build/
    just --justfile $HOME/devc/i/devc1/justfile pv --log-level=ALL:DEBUG --set-default-native-engine=Ignite --local-native-path=$(realpath $HOME/devc/i/devc1/build/libamzn_ignite_sdk_rust_examples.so) --log-file=build/log-ignite-$(date +%F-%H-%M-%S).txt

[no-cd]
native_app:
    #!/usr/bin/env zsh
    name=native_app just run "
        cd ../AVLivingRoomRustClient/crates/app-start &&
        just pre_build ../.. &&
        cargo build -p amzn-av-living-room-rust-client --lib --features=amzn-ignx-compositron/allow_no_js_vm,amzn-ignx-compositron/use_ignx_local
    "

[no-cd]
native_example:
    #!/usr/bin/env zsh
    name=native_example just run "
        cd ../AVLivingRoomRustClient/crates/app-start &&
        just pre_build ../.. &&
        cargo build -p amzn-av-living-room-rust-client --lib --features=amzn-ignx-compositron/allow_no_js_vm,amzn-ignx-compositron/use_ignx_local
    "

[no-cd]
native_roku:
    #!/usr/bin/env zsh
    name=native_roku just run "
        cd ../AVLivingRoomRustClient/crates/app-start &&
        just pre_build ../.. &&
        cargo build -p amzn-av-living-room-rust-client --lib --features=amzn-ignx-compositron/use_ignx_local --target=arm-unknown-linux-gnueabi
    "

# Log in or run command on $(whoami)-1c-1d10d9ca.eu-west-1.amazon.com
c *command: mwinit
    #!/usr/bin/env bash
    set -euo pipefail
    if command -v zellij &>/dev/null; then
        if [ -n "{{ command }}" ]; then
            session="c: {{ command }}"
            ssh c "zellij attach -b -c '$session'" 2>/dev/null || true
            ssh c "ZELLIJ_SESSION_NAME='$session' zellij run -- bash -c '
                {{ command }}
                rc=\$?
                if [ \$(zellij action list-clients 2>/dev/null | wc -l) -le 1 ]; then
                    echo -e \"\\n[exit \$rc] Waiting for client to attach...\"
                    while [ \$(zellij action list-clients 2>/dev/null | wc -l) -le 1 ]; do sleep 1; done
                fi
                exit \$rc
            '"
            ssh -t c "zellij attach '$session'"
        else
            ssh -t c 'zellij attach -c c'
        fi
    else
        ssh {{ if command == "" { "" } else { "-t" } }} c "{{ command }}"
    fi

[no-cd]
cp src dst=".": mwinit
    scp -r "c:{{ src }}" "{{ dst }}"

# Run `eval $(just setup_shell)` for aliases (jbuild, jrelase, etc) and command completion
setup_shell:
    #!/usr/bin/env zsh
    for recipe in `just --summary`
    do
        echo "alias j$recipe=\"just $recipe\""
    done
    echo "alias jm=\"just mwinit\""
    echo "alias jmf=\"just mwinitf\""

    just --completions $(basename $SHELL)

alias m := mwinit
alias mf := mwinitf
