import 'recurse-brazil.just'

# FIXME doc no-cd

init_AVLivingRoomClientHybridCommon:
    brazil-build install

build_AVLivingRoomClientHybridCommon:
    brazil-build release

build_AVLivingRoomClientBootstrap:
    brazil-build

init_AVLivingRoomClient:
    brazil-build install

build_AVLivingRoomClient:
    brazil-build run build-prod -- --env deviceType=Default-Ignite-XP --env sourceMap=eval-source-map

build_RokuNDK:
    brazil-build

pre_build_RustStdRoku:
    rm -f build/private/src/config.toml

build_RustStdRoku:
    brazil-build

init_Brotli:
    git checkout --force origin/Brotli-1.1.0

build_Brotli:
    brazil-build

init_AVLivingRoomRustClient:
    brazil-build build || true
    cargo brazil fetch --target all

pre_build_AVLivingRoomRustClient:
    rm -f Cargo.lock

build_AVLivingRoomRustClient:
    build-tools/bin/generate-bundles native
    #build-tools/bin/generate-bundles all
    #brazil-build build

    find build/ -regex .\*amzn_av_living_room_rust_client.\*so | xargs --no-run-if-empty ls -l
    find build/ -regex .\*amzn_av_living_room_rust_client.\*so | xargs --no-run-if-empty file
    find build/ -regex .\*amzn_av_living_room_rust_client.\*so.br | xargs --no-run-if-empty file

build_AVLivingRoomClientBundle:
    brazil-build run build -- -f Ignition-X-XP --nobytecode --noaot --nothreads --nonativebundle=false

release_AVLivingRoomClientBundle:
    brazil-build run put-this-on-that -- --flavor Ignition-X-XP --dtid=A3VN4E5F7BBC7S --did=abcd$(whoami)abcd --stringBundles en_US

[no-cd]
native_app:
    #!/usr/bin/env zsh
    name=native_app just run "
        just pre_build &&
        cd ../AVLivingRoomRustClient/crates/app-start &&
        cargo build -p amzn-av-living-room-rust-client --lib --features=amzn-ignx-compositron/allow_no_js_vm,amzn-ignx-compositron/use_ignx_local
    "

[no-cd]
native_example:
    #!/usr/bin/env zsh
    name=native_example just run "
        just pre_build &&
        cd ../AVLivingRoomRustClient/crates/app-start &&
        cargo build -p amzn-av-living-room-rust-client --lib --features=amzn-ignx-compositron/allow_no_js_vm,amzn-ignx-compositron/use_ignx_local
    "

[no-cd]
native_roku:
    #!/usr/bin/env zsh
    name=native_roku just run "
        just pre_build &&
        cd ../AVLivingRoomRustClient/crates/app-start &&
        cargo build -p amzn-av-living-room-rust-client --lib --features=amzn-ignx-compositron/allow_no_js_vm,amzn-ignx-compositron/use_ignx_local --target=arm-unknown-linux-gnueabi
    "

[no-cd]
bundle_native:
    #!/usr/bin/env zsh
    name=bundle_native just run "
        fd -tf amzn_av_living_room_rust_client.\*so build/ | xargs rm
        build-tools/bin/generate-bundles native &&
            fd -ltf amzn_av_living_room_rust_client.\*so build/ &&
            fd -tf amzn_av_living_room_rust_client.\*so build/ | xargs file
    "

c *command: mwinit
    ssh dev-dsk-$(whoami)-1c-1d10d9ca.eu-west-1.amazon.com "{{ command }}"

# Run `eval $(just setup_shell)` for aliases (jbuild, jrelase, etc) and command completion
setup_shell:
    #!/usr/bin/env zsh
    for recipe in `just --summary`
    do
        echo "alias j$recipe=\"just $recipe\""
    done
    echo "alias jm=\"just mwinit\""
    echo "alias jmf=\"just mwinitf\""

    just --completions $(basename $SHELL)

alias m := mwinit
alias mf := mwinitf
