# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.22)
{
  
  description = "My Neovim";

  
  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
  };

  
  outputs = { self, flake-schemas, nixpkgs }:
    let
      
      supportedSystems = [ "x86_64-linux" "aarch64-darwin" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in {
      
      schemas = flake-schemas.schemas;

      
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          
          packages = with pkgs; [
            git
            neovim
            nodejs  # biome from Mason
            uv  # nvim-dap-python
          ];

          
          shellHook = ''
            exec nvim
          '';
        };
      });
    };
}
