#!env zsh
local TARGETS=${FA_TARGETS:-$(find . -mindepth 1 -maxdepth 1 -type d)}
# turning on SH_WORD_SPLIT as http://zsh.sourceforge.net/FAQ/zshfaq03.html
for TARGET in ${=TARGETS}
do
	echo "$TARGET:"
	(cd $TARGET; "$@")
	echo
done
# refer to smart_sudo in http://zshwiki.org/home/examples/functions
#alias fa='_fa '
