#!env zsh
_FA_TARGETS=${FA_TARGETS:-$(realpath
                                $(echo $(git rev-parse --show-toplevel 2> /dev/null)/../*/ ||
                                    echo */)
                            )}
local TARGET
# turning on SH_WORD_SPLIT as http://zsh.sourceforge.net/FAQ/zshfaq03.html
for TARGET in ${=_FA_TARGETS}
do
	echo ">>>> $TARGET:"
    (cd $TARGET; "$@") || return $?
done
# refer to smart_sudo in http://zshwiki.org/home/examples/functions
#alias fa='_fa '
