#!env zsh
_FA_TARGETS=${FA_TARGETS:-$(echo $(realpath $(git rev-parse --show-toplevel || echo .)/../*/))}
local TARGET
# turning on SH_WORD_SPLIT as http://zsh.sourceforge.net/FAQ/zshfaq03.html
for TARGET in ${=_FS_TARGETS}
do
	echo -n "${TARGET##*/}:¬"
	(cd $TARGET; "$@") 2> /dev/null || echo
done | column -s '¬' -t
