#!env zsh
FILES_TO_WATCH=${FILES_TO_WATCH:-.}
PS4="+++++++++++++++++++++++++++++ "
D=1 
set -x
while [ -n "$(fd --changed-after @$D | head -1)" ] || (
    inotifywait -e modify -r ${FILES_TO_WATCH}
    while inotifywait -e modify -r ${FILES_TO_WATCH} -t 10
    do
        :
    done
)
do
    D=$(date +%s) 
    time "$@"
    date
done
