#!env zsh
#python crashlog_printer.py -c cache0413 859800641
#python crashlog_printer.py -c cache0414 860722067
#python crashlog_printer.py -c cache0415 861600616
#python crashlog_printer.py -c cache0416 862600059
#python crashlog_printer.py -c cache0417 863522167
#python crashlog_printer.py -c cache0418 864456477
#python crashlog_printer.py -c cache0419 865352304
#python crashlog_printer.py -c cache0420 866250601
#python crashlog_printer.py -c cache0421 867147125
#python crashlog_printer.py -c cache0422 868027995
#python crashlog_printer.py -c cache0423 869065473
#python crashlog_printer.py -c cache0424 869991133

(
	AWK_DELETE_TEST_DEVICES=$(awk -F '[,"]' '
		$5 != "" {printf("/%s/{next}", $5)}
		' test_devices*.txt)

	echo "chipset #session #crash #rubycrash crash-rate% non-ruby-crash-rate%"
	for CHIPSET in ",H15_W30=1" ",K2LP_W30=1" ",K2L_W30=1" ",M16LITE_W30=1" ",M16_W30=1" ",M2_W30=1" "."
	do
		CHIPSET_NAME="${${CHIPSET#,}%_W30=1} "
		#echo " dir #session #crash #rubycrash crash-rate% non-ruby-crash-rate%"
		#for CACHE in $(ls -d cache*)
		#do
			find *1{8,9} *2{0,1,2,3,4} -name '*.txt' |\
			awk "$AWK_DELETE_TEST_DEVICES{print}" |\
			xargs grep -L ',.[012]\...\...=1,\|UnknownFirmware' |\
			xargs grep -h "${CHIPSET}" |\
			awk "
				BEGIN	{crash=0;rubycrash=0}
				/IgnitionStartup/	{session++}
				/EnterForegroundJS/	{session++}
				/IgnitionSignalCrash/	{crash++}
				/IgnitionCrashDump.*NetworkMonitor/	{rubycrash++}
				END	{
						print \"$CHIPSET_NAME\",
								session,
								crash,
								rubycrash,
								(session!=0)?crash*100/session:0,
								(session!=0)?(crash-rubycrash)*100/session:0
				}
			"
		#done
	done
) | tee >(column -t)	# http://unix.stackexchange.com/a/28519
