#!env zsh
this_dir="$(realpath $(pwd))"
parent_dir="$(realpath $(pwd)/..)"
git_dir="$(realpath $(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null))"
new_home="${DOCKER_HERE_HOME}"
test -n "${new_home}" && new_path_array=($(ls -d ${new_home} ${new_home}/*/ ${new_home}/*/bin ${new_home}/.*/bin 2>/dev/null || true))
test -n "${new_home}" && new_path=$(print -R ${(j|:|)new_path_array})

all_signle_options=(-d --detach --init -i --interactive --no-healthcheck --oom-kill--disable --privileged -P --publish-all --read-only --rm --sig-proxy -t --tty) # from docker run --help (20.10.25)
single_options=()
double_options=()
while [[ "$1" = -* ]]
do
    if [[ " ${all_signle_options[@]} " =~ " $1 " ]]
    then
        single_options+=($1)
        shift
    else
        double_options+=("$1" "$2")
        shift 2
    fi
done

image="${1}"
shift

test -f /tmp/fake_passwd || echo "$(id -un):x:$(id -u):$(id -g):Git User:/tmp:/bin/bash" > /tmp/fake_passwd

# --init is needed for xvfb-run to run
# --tty shows colour in the terminal
docker run \
    --init \
    --tty \
    --user $(id -u):$(id -g) \
    --volume "${parent_dir}:${parent_dir}" \
    ${new_home:+--volume} ${new_home:+"${new_home}:${new_home}"} \
    ${new_home:+--volume} ${new_home:+"$HOME/.ssh:${new_home}/.ssh"} \
    --volume /tmp/fake_passwd:/etc/passwd  \
    --workdir "${this_dir}" \
    --env AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id 2>/dev/null||true)" \
    --env AWS_SECRET_ACCESS_KEY="$(aws configure get aws_secret_access_key 2>/dev/null||true)" \
    --env AWS_SESSION_TOKEN="$(aws configure get aws_session_token 2>/dev/null||true)" \
    --env GIT_SSH_COMMAND="${new_home:+ssh -i ${new_home}/.ssh/id_ecdsa -i ${new_home}/.ssh/id_ed25519 -o 'StrictHostKeyChecking=no'}" \
    "${single_options[@]}" "${double_options[@]}" \
    "${image}" \
    bash -c "
        export HOME=${new_home:-\$HOME}
        export PATH=${new_path}:\${PATH}
        $*"
    #--volume "${this_dir}:${this_dir}" \
    #--volume "${git_dir}:${git_dir}" \
