#!env zsh
if (( $# == 0 ))
then
	export FA_TARGETS=
else
	export FA_TARGETS="$(find "$@" -mindepth 1 -maxdepth 1 -type d -name .git -print0|xargs -0r readlink -f|xargs dirname)"
fi
echo "FA_TARGETS=${FA_TARGETS}"
