#!env zsh
nix_develop_command() { which nix &> /dev/null && test -f flake.nix && echo "nix develop path:. --command" }
just --justfile ~/.justfile log_prefix_ignore="$(nix_develop_command) just" run $(nix_develop_command) just "$@"
