#!env zsh
# Run an arbitrary shell command with set -x and time. Logging is handled
# by the zz-logrun-auto.zsh widget on the outer prompt invocation
# (when `jr` is in LOGRUN_AUTO_FUNCTIONS).
set -x
time "$@"
