#!env zsh
# Run an arbitrary shell command through `logrun` (no nix devshell, no just).
logrun --name "${*:-jr}" --log-dir "${build_dir:-/tmp/logrun/${${PWD#$HOME/}//\//-}}" -c "
    set -x
    time ${(j: :)${(q-)@}}
"
