#!env zsh
local grep_pattern="${${@/#/\b}/%/\b}"

command which -a "$@" |
    grep -iv "not found" |
    grep -iv "no $@ in (" |
    tee >(cat - >&2) |
    xargs strings |
    head -40

# fun in keys of ${functions} associative array with keys starting with "_" removed
for fun in ${(k)=functions:/_*/}
do
	autoload +X -- $fun
	functions -- $fun | grep -q "${grep_pattern}" && functions $fun | head -40
done

# functions which are prefixed with "aliased_" which are added from ../functions.zsh
functions "${@/#/aliased_}"

alias|grep "${grep_pattern}"

# tldr shows the error message to stdout, not stderr
tldr "$@" >/dev/null 2>&1 && tldr "$@"
