#!env zsh	# This is only for sourcing
local grep_pattern="${${@/#/\b}/%/\b}"
# fun in keys of ${functions} associative array with keys starting with "_" removed
for fun in ${(k)=functions:/_*/}
do
	autoload +X -- $fun
	functions -- $fun | grep -q "${grep_pattern}" && functions $fun | head -40
done

which -p "$@" | grep -iv "not found" | xargs head -40

alias|grep "${grep_pattern}"

# functions which are prefixed with "aliased_" which are added from ../functions.zsh
functions "${@/#/aliased_}"

functions "$@"

# tldr shows the error message to stdout, not stderr
tldr "$@" >/dev/null 2>&1 && tldr "$@"

