#!env zsh
nix_develop_command() {
    which nix &> /dev/null &&
        test ! -f flake.nix &&
        return

    git ls-files | grep '^flake.nix$' &> /dev/null &&
        echo "nix develop --impure --command" ||
        echo "nix develop path:. --impure --command"
}
$(nix_develop_command) "$@"
