#!env zsh
nix_develop_command() {
    which nix &> /dev/null &&
        test ! -f flake.nix &&
        return

    git ls-files | grep '^flake.nix$' &> /dev/null &&
        echo "nix develop --ignore-env --command" ||
        echo "nix develop path:. --ignore-env --command"
}
$(nix_develop_command) just --justfile ~/.justfile run "$@"
