#!env zsh

OPEN=$(which wslview 2> /dev/null)
if [ "$?" -eq 0 ]
then
    ${OPEN} "$(wslpath -w "$(realpath "$@")")"
    return
fi

OPEN=$(which open 2> /dev/null)
if [ "$?" -eq 0 ]
then
    ${OPEN} "$@"
    return
fi

echo "No sciprt for $(uname -ro)" 1>&2
return 1
