#!/usr/bin/env bash
GIT=${GIT_EXECUTABLE:-git}
GIT_SUBREPO=${GIT_SUBREPO:-git-subrepo}
cd $1 || {echo "NO DIRECTORY: $1"; exit}

$GIT add --all .
$GIT commit -m "Change from $(hostname -s)"
$GIT pull --no-edit --recurse-submodules=no \
    || $GIT merge --abort \
    && $GIT push \
    && $GIT_SUBREPO pull -v --all \
    || $GIT_SUBREPO clean --all

$GIT submodule foreach bash -c "$GIT add --all . ;\
    $GIT commit -m \"Change from $(hostname -s)\" && WILL_PUSH=yes ;\
    $GIT pull --no-edit --recurse-submodules=no ;\
    test \$WILL_PUSH && $GIT push || true"
