users.users.myuser = {
  isNormalUser = true;
  description = "My Personal User";
  extraGroups = [ "wheel" "networkmanager" ]; # 'wheel' for sudo, 'networkmanager' for network management
  packages = with pkgs; [
    firefox
    git
  ];
  # hashed password generated by mkpasswd -m sha512
  hashedPassword = "$6$.............................................";
};

