#!/usr/bin/env -S just --justfile

import? '~/.justfile'

[private]
default:
    @just --list --unsorted

all: sysroots toolchain mixed sye symbol_wrapper

clean: clean_mixed clean_musl
    rm -rf sysroots/ install/

clean_all:
    rm -rf build/{llvm,sysroots,examples,sye} sysroots/ install/

sdk:
    ./build_sysroots.sh
    ./build_toolchain.sh
    ./build_examples.sh mixed

sysroots:
    ./build_sysroots.sh

toolchain:
    ./build_toolchain.sh

mixed:
    rm -rf build/examples/mixed/
    ./build_examples.sh mixed
    readelf --all build/examples/mixed/x86_64-unknown-linux-gnu/libmixed.so | grep toupper

clean_mixed:
    rm -rf build/examples/mixed/

musl:
    #!/usr/bin/env zsh
    set -xe -o pipefail

    SCRIPT_DIR=$(pwd)
    targets=(
        "x86_64-unknown-linux-gnu"
        #"armv7-unknown-linux-gnueabihf"
        #"armv7-unknown-linux-gnueabi"
        #"aarch64-unknown-linux-gnu"
    )

    for target in "${targets[@]}"; do
        mkdir -p "$SCRIPT_DIR/build/sysroots/musl-${target}"
        cd "$SCRIPT_DIR/build/sysroots/musl-${target}"
        export AR="$SCRIPT_DIR/build/llvm/bin/llvm-ar"
        export RANLIB="$SCRIPT_DIR/build/llvm/bin/llvm-ranlib"
        export CC="$SCRIPT_DIR/build/llvm/bin/clang --no-default-config --target=${target} --rtlib=compiler-rt -fuse-ld=lld -fno-stack-protector --sysroot=$SCRIPT_DIR/sysroots/${target}/"
        export LIBCC="$SCRIPT_DIR/build/sysroots/builtins-${target}/lib/${target}/libclang_rt.builtins.a"
        "$SCRIPT_DIR/external/musl/configure" --target="${target}" --srcdir="$SCRIPT_DIR/external/musl" --prefix="$SCRIPT_DIR/sysroots/${target}/usr" --disable-gcc-wrapper --disable-shared
        make -j64 install
    done

    readelf --all build/sysroots/musl-x86_64-unknown-linux-gnu/lib/libc.a | grep iswupper_l

clean_musl:
    rm -rf build/sysroots/musl*

sye:
    #!/usr/bin/env zsh
    set -xe -o pipefail

    #-DCMAKE_SHARED_LINKER_FLAGS="-Wl,--trace-symbol,iswprint_l -Wl,--trace-symbol,iswalpha_l -Wl,--trace-symbol,iswupper_l -Wl,--trace-symbol,uselocale -Wl,--trace-symbol,isupper_l -Wl,--trace-symbol,iswspace_l -Wl,--trace-symbol,iswblank_l -Wl,--trace-symbol,strxfrm_l -Wl,--trace-symbol,iswpunct_l -Wl,--trace-symbol,isxdigit_l -Wl,--trace-symbol,wcsxfrm_l -Wl,--trace-symbol,newlocale -Wl,--trace-symbol,isdigit_l -Wl,--trace-symbol,strftime_l -Wl,--trace-symbol,strcoll_l -Wl,--trace-symbol,toupper_l -Wl,--trace-symbol,freelocale -Wl,--trace-symbol,towlower_l -Wl,--trace-symbol,iswxdigit_l -Wl,--trace-symbol,iswlower_l -Wl,--trace-symbol,towupper_l -Wl,--trace-symbol,tolower_l -Wl,--trace-symbol,iswcntrl_l -Wl,--trace-symbol,islower_l -Wl,--trace-symbol,iswdigit_l -Wl,--trace-symbol,wcscoll_l -Wl,--trace-symbol,wcscoll_l " \
    #-DCMAKE_SHARED_LINKER_FLAGS="-Wl,--trace-symbol,pthread_cond_broadcast -Wl,--trace-symbol,pthread_mutexattr_destroy -Wl,--trace-symbol,pthread_key_create -Wl,--trace-symbol,pthread_cond_wait -Wl,--trace-symbol,pthread_mutexattr_init -Wl,--trace-symbol,pthread_cond_signal -Wl,--trace-symbol,pthread_setspecific  -Wl,--trace-symbol,pthread_once -Wl,--trace-symbol,pthread_cond_timedwait -Wl,--trace-symbol,pthread_cond_destroy -Wl,--trace-symbol,pthread_mutex_init -Wl,--trace-symbol,pthread_join  -Wl,--trace-symbol,pthread_mutex_lock -Wl,--trace-symbol,pthread_mutex_destroy -Wl,--trace-symbol,pthread_detach -Wl,--trace-symbol,pthread_mutex_trylock -Wl,--trace-symbol,pthread_getspecific -Wl,--trace-symbol,pthread_mutexattr_settype -Wl,--trace-symbol,pthread_create -Wl,--trace-symbolpthread_self -Wl,--trace-symbol,pthread_mutex_unlock " \

    export BUILD_TARGET=x86_64-unknown-linux-gnu
    cmake ../syewasmbundle \
        -Bbuild/sye \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_TOOLCHAIN_FILE=$(pwd)/toolchain.cmake \
        -DPLATFORM_NAME=native \
        -G Ninja

    cmake --build build/sye --target sye_wasm_bundle

    readelf -s build/sye/src/wasm_bundle/libsye_wasm_bundle.so | grep "WEAK .* iswupper_l"
    readelf -s build/sye/src/wasm_bundle/libsye_wasm_bundle.so | grep "UND pthread_create"

clean_sye:
    rm -rf build/sye

symbol_wrapper:
    #!/usr/bin/env zsh
    set -xe -o pipefail

    DIR=$(pwd)
    cd ../i/devc1/src/elf-loader/scripts/posix_emu

    nd() { which nix &> /dev/null && test -f ../flake.nix && echo "nix develop .. --command" }
    $(nd) python3 ../symbol_wrapper.py $DIR/../syewasmbundle/build-native/src/wasm_bundle/libsye_wasm_bundle.so $DIR/sysroots/x86_64-unknown-linux-gnu

ignite_test_assets:
    ../i/devc1/tests/assets/elf/build.sh $(pwd)

clean_ignite_test_assets:
    rm -rf ../i/devc1/tests/assets/elf/build/*
